# Generated by Django 4.2.3 on 2023-07-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '任务信息', 'verbose_name_plural': '任务内容'},
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('u', '还未开始的活动'), ('o', '正在进行的活动'), ('f', '已经完成的活动')], max_length=1, verbose_name='活动类型'),
        ),
    ]
